package dracocore.blocks.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelManaPipe extends ModelBase
{
  //fields
    ModelRenderer Center1;
    ModelRenderer Center2;
    ModelRenderer Center3;
    ModelRenderer Center4;
    ModelRenderer Center5;
    ModelRenderer Center6;
    public ModelRenderer FrontPipe;
    public ModelRenderer BackPipe;
    public ModelRenderer LeftPipe;
    public ModelRenderer RightPipe;
    public ModelRenderer TopPipe;
    public ModelRenderer BottomPipe;
    public ModelRenderer ManaTransducerFront;
    public ModelRenderer ManaTransducerArmFront1;
    public ModelRenderer ManaTransducerArmFront2;
    public ModelRenderer ManaTransducerArmFront3;
    public ModelRenderer ManaTransducerArmFront4;
    public ModelRenderer ManaTransducerBack;
    public ModelRenderer ManaTransducerArmBack1;
    public ModelRenderer ManaTransducerArmBack2;
    public ModelRenderer ManaTransducerArmBack3;
    public ModelRenderer ManaTransducerArmBack4;
    public ModelRenderer ManaTransducerRight;
    public ModelRenderer ManaTransducerArmRight1;
    public ModelRenderer ManaTransducerArmRight2;
    public ModelRenderer ManaTransducerArmRight3;
    public ModelRenderer ManaTransducerArmRight4;
    public ModelRenderer ManaTransducerLeft;
    public ModelRenderer ManaTransducerArmLeft1;
    public ModelRenderer ManaTransducerArmLeft2;
    public ModelRenderer ManaTransducerArmLeft3;
    public ModelRenderer ManaTransducerArmLeft4;
    public ModelRenderer ManaTransducerUp;
    public ModelRenderer ManaTransducerArmUp1;
    public ModelRenderer ManaTransducerArmUp2;
    public ModelRenderer ManaTransducerArmUp3;
    public ModelRenderer ManaTransducerArmUp4;
    public ModelRenderer ManaTransducerDown;
    public ModelRenderer ManaTransducerArmDown1;
    public ModelRenderer ManaTransducerArmDown2;
    public ModelRenderer ManaTransducerArmDown3;
    public ModelRenderer ManaTransducerArmDown4;
  
  public ModelManaPipe()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Center1 = new ModelRenderer(this, 0, 0);
      Center1.addBox(-1F, -2F, -1F, 2, 1, 2);
      Center1.setRotationPoint(0F, 16F, 0F);
      Center1.setTextureSize(128, 64);
      Center1.mirror = true;
      setRotation(Center1, 0F, 0F, 0F);
      Center2 = new ModelRenderer(this, 0, 5);
      Center2.addBox(1F, -1F, -1F, 1, 2, 2);
      Center2.setRotationPoint(0F, 16F, 0F);
      Center2.setTextureSize(128, 64);
      Center2.mirror = true;
      setRotation(Center2, 0F, 0F, 0F);
      Center3 = new ModelRenderer(this, 9, 0);
      Center3.addBox(-1F, 1F, -1F, 2, 1, 2);
      Center3.setRotationPoint(0F, 16F, 0F);
      Center3.setTextureSize(128, 64);
      Center3.mirror = true;
      setRotation(Center3, 0F, 0F, 0F);
      Center4 = new ModelRenderer(this, 9, 5);
      Center4.addBox(-1F, -1F, 1F, 2, 2, 1);
      Center4.setRotationPoint(0F, 16F, 0F);
      Center4.setTextureSize(128, 64);
      Center4.mirror = true;
      setRotation(Center4, 0F, 0F, 0F);
      Center5 = new ModelRenderer(this, 19, 0);
      Center5.addBox(-2F, -1F, -1F, 1, 2, 2);
      Center5.setRotationPoint(0F, 16F, 0F);
      Center5.setTextureSize(128, 64);
      Center5.mirror = true;
      setRotation(Center5, 0F, 0F, 0F);
      Center6 = new ModelRenderer(this, 19, 5);
      Center6.addBox(-1F, -1F, -2F, 2, 2, 1);
      Center6.setRotationPoint(0F, 16F, 0F);
      Center6.setTextureSize(128, 64);
      Center6.mirror = true;
      setRotation(Center6, 0F, 0F, 0F);
      FrontPipe = new ModelRenderer(this, 15, 11);
      FrontPipe.addBox(-0.5F, -0.5F, -8F, 1, 1, 6);
      FrontPipe.setRotationPoint(0F, 16F, 0F);
      FrontPipe.setTextureSize(128, 64);
      FrontPipe.mirror = true;
      setRotation(FrontPipe, 0F, 0F, 0F);
      BackPipe = new ModelRenderer(this, 0, 11);
      BackPipe.addBox(-0.5F, -0.5F, 2F, 1, 1, 6);
      BackPipe.setRotationPoint(0F, 16F, 0F);
      BackPipe.setTextureSize(128, 64);
      BackPipe.mirror = true;
      setRotation(BackPipe, 0F, 0F, 0F);
      LeftPipe = new ModelRenderer(this, 0, 19);
      LeftPipe.addBox(2F, -0.5F, -0.5F, 6, 1, 1);
      LeftPipe.setRotationPoint(0F, 16F, 0F);
      LeftPipe.setTextureSize(128, 64);
      LeftPipe.mirror = true;
      setRotation(LeftPipe, 0F, 0F, 0F);
      RightPipe = new ModelRenderer(this, 0, 22);
      RightPipe.addBox(-8F, -0.5F, -0.5F, 6, 1, 1);
      RightPipe.setRotationPoint(0F, 16F, 0F);
      RightPipe.setTextureSize(128, 64);
      RightPipe.mirror = true;
      setRotation(RightPipe, 0F, 0F, 0F);
      TopPipe = new ModelRenderer(this, 5, 25);
      TopPipe.addBox(-0.5F, -8F, -0.5F, 1, 6, 1);
      TopPipe.setRotationPoint(0F, 16F, 0F);
      TopPipe.setTextureSize(128, 64);
      TopPipe.mirror = true;
      setRotation(TopPipe, 0F, 0F, 0F);
      BottomPipe = new ModelRenderer(this, 0, 25);
      BottomPipe.addBox(-0.5F, 2F, -0.5F, 1, 6, 1);
      BottomPipe.setRotationPoint(0F, 16F, 0F);
      BottomPipe.setTextureSize(128, 64);
      BottomPipe.mirror = true;
      setRotation(BottomPipe, 0F, 0F, 0F);
      ManaTransducerFront = new ModelRenderer(this, 32, 0);
      ManaTransducerFront.addBox(-1.5F, -1.5F, -8F, 3, 3, 1);
      ManaTransducerFront.setRotationPoint(0F, 16F, 0F);
      ManaTransducerFront.setTextureSize(128, 64);
      ManaTransducerFront.mirror = true;
      setRotation(ManaTransducerFront, 0F, 0F, 0F);
      ManaTransducerArmFront1 = new ModelRenderer(this, 32, 5);
      ManaTransducerArmFront1.addBox(-6.5F, -0.5F, -7F, 3, 1, 1);
      ManaTransducerArmFront1.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmFront1.setTextureSize(128, 64);
      ManaTransducerArmFront1.mirror = true;
      setRotation(ManaTransducerArmFront1, 0F, -0.3490659F, 0F);
      ManaTransducerArmFront2 = new ModelRenderer(this, 32, 8);
      ManaTransducerArmFront2.addBox(3.5F, -0.5F, -7F, 3, 1, 1);
      ManaTransducerArmFront2.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmFront2.setTextureSize(128, 64);
      ManaTransducerArmFront2.mirror = true;
      setRotation(ManaTransducerArmFront2, 0F, 0.3490659F, 0F);
      ManaTransducerArmFront3 = new ModelRenderer(this, 41, 0);
      ManaTransducerArmFront3.addBox(-0.5F, 3.5F, -7F, 1, 3, 1);
      ManaTransducerArmFront3.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmFront3.setTextureSize(128, 64);
      ManaTransducerArmFront3.mirror = true;
      setRotation(ManaTransducerArmFront3, -0.3490659F, 0F, 0F);
      ManaTransducerArmFront4 = new ModelRenderer(this, 41, 5);
      ManaTransducerArmFront4.addBox(-0.5F, -6.5F, -7F, 1, 3, 1);
      ManaTransducerArmFront4.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmFront4.setTextureSize(128, 64);
      ManaTransducerArmFront4.mirror = true;
      setRotation(ManaTransducerArmFront4, 0.3490659F, 0F, 0F);
      ManaTransducerBack = new ModelRenderer(this, 32, 14);
      ManaTransducerBack.addBox(-1.5F, -1.5F, 7F, 3, 3, 1);
      ManaTransducerBack.setRotationPoint(0F, 16F, 0F);
      ManaTransducerBack.setTextureSize(128, 64);
      ManaTransducerBack.mirror = true;
      setRotation(ManaTransducerBack, 0F, 0F, 0F);
      ManaTransducerArmBack1 = new ModelRenderer(this, 41, 14);
      ManaTransducerArmBack1.addBox(-0.5F, -6.5F, 6F, 1, 3, 1);
      ManaTransducerArmBack1.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmBack1.setTextureSize(128, 64);
      ManaTransducerArmBack1.mirror = true;
      setRotation(ManaTransducerArmBack1, -0.3490659F, 0F, 0F);
      ManaTransducerArmBack2 = new ModelRenderer(this, 41, 19);
      ManaTransducerArmBack2.addBox(-0.5F, 3.5F, 6F, 1, 3, 1);
      ManaTransducerArmBack2.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmBack2.setTextureSize(128, 64);
      ManaTransducerArmBack2.mirror = true;
      setRotation(ManaTransducerArmBack2, 0.3490659F, 0F, 0F);
      ManaTransducerArmBack3 = new ModelRenderer(this, 32, 19);
      ManaTransducerArmBack3.addBox(3.5F, -0.5F, 6F, 3, 1, 1);
      ManaTransducerArmBack3.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmBack3.setTextureSize(128, 64);
      ManaTransducerArmBack3.mirror = true;
      setRotation(ManaTransducerArmBack3, 0F, -0.3490659F, 0F);
      ManaTransducerArmBack4 = new ModelRenderer(this, 32, 22);
      ManaTransducerArmBack4.addBox(-6.5F, -0.5F, 6F, 3, 1, 1);
      ManaTransducerArmBack4.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmBack4.setTextureSize(128, 64);
      ManaTransducerArmBack4.mirror = true;
      setRotation(ManaTransducerArmBack4, 0F, 0.3490659F, 0F);
      ManaTransducerRight = new ModelRenderer(this, 48, 0);
      ManaTransducerRight.addBox(-8F, -1.5F, -1.5F, 1, 3, 3);
      ManaTransducerRight.setRotationPoint(0F, 16F, 0F);
      ManaTransducerRight.setTextureSize(128, 64);
      ManaTransducerRight.mirror = true;
      setRotation(ManaTransducerRight, 0F, 0F, 0F);
      ManaTransducerArmRight1 = new ModelRenderer(this, 57, 0);
      ManaTransducerArmRight1.addBox(-7F, 3.5F, -0.5F, 1, 3, 1);
      ManaTransducerArmRight1.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmRight1.setTextureSize(128, 64);
      ManaTransducerArmRight1.mirror = true;
      setRotation(ManaTransducerArmRight1, 0F, 0F, 0.3490659F);
      ManaTransducerArmRight2 = new ModelRenderer(this, 57, 5);
      ManaTransducerArmRight2.addBox(-7F, -6.5F, -0.5F, 1, 3, 1);
      ManaTransducerArmRight2.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmRight2.setTextureSize(128, 64);
      ManaTransducerArmRight2.mirror = true;
      setRotation(ManaTransducerArmRight2, 0F, 0F, -0.3490659F);
      ManaTransducerArmRight3 = new ModelRenderer(this, 48, 7);
      ManaTransducerArmRight3.addBox(-7F, -0.5F, -6.5F, 1, 1, 3);
      ManaTransducerArmRight3.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmRight3.setTextureSize(128, 64);
      ManaTransducerArmRight3.mirror = true;
      setRotation(ManaTransducerArmRight3, 0F, 0.3490659F, 0F);
      ManaTransducerArmRight4 = new ModelRenderer(this, 48, 12);
      ManaTransducerArmRight4.addBox(-7F, -0.5F, 3.5F, 1, 1, 3);
      ManaTransducerArmRight4.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmRight4.setTextureSize(128, 64);
      ManaTransducerArmRight4.mirror = true;
      setRotation(ManaTransducerArmRight4, 0F, -0.3490659F, 0F);
      ManaTransducerLeft = new ModelRenderer(this, 48, 19);
      ManaTransducerLeft.addBox(7F, -1.5F, -1.5F, 1, 3, 3);
      ManaTransducerLeft.setRotationPoint(0F, 16F, 0F);
      ManaTransducerLeft.setTextureSize(128, 64);
      ManaTransducerLeft.mirror = true;
      setRotation(ManaTransducerLeft, 0F, 0F, 0F);
      ManaTransducerArmLeft1 = new ModelRenderer(this, 57, 19);
      ManaTransducerArmLeft1.addBox(6F, -6.5F, -0.5F, 1, 3, 1);
      ManaTransducerArmLeft1.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmLeft1.setTextureSize(128, 64);
      ManaTransducerArmLeft1.mirror = true;
      setRotation(ManaTransducerArmLeft1, 0F, 0F, 0.3490659F);
      ManaTransducerArmLeft2 = new ModelRenderer(this, 48, 26);
      ManaTransducerArmLeft2.addBox(6F, -0.5F, 3.5F, 1, 1, 3);
      ManaTransducerArmLeft2.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmLeft2.setTextureSize(128, 64);
      ManaTransducerArmLeft2.mirror = true;
      setRotation(ManaTransducerArmLeft2, 0F, 0.3490659F, 0F);
      ManaTransducerArmLeft3 = new ModelRenderer(this, 57, 24);
      ManaTransducerArmLeft3.addBox(6F, 3.5F, -0.5F, 1, 3, 1);
      ManaTransducerArmLeft3.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmLeft3.setTextureSize(128, 64);
      ManaTransducerArmLeft3.mirror = true;
      setRotation(ManaTransducerArmLeft3, 0F, 0F, -0.3490659F);
      ManaTransducerArmLeft4 = new ModelRenderer(this, 48, 31);
      ManaTransducerArmLeft4.addBox(6F, -0.5F, -6.5F, 1, 1, 3);
      ManaTransducerArmLeft4.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmLeft4.setTextureSize(128, 64);
      ManaTransducerArmLeft4.mirror = true;
      setRotation(ManaTransducerArmLeft4, 0F, -0.3490659F, 0F);
      ManaTransducerUp = new ModelRenderer(this, 65, 0);
      ManaTransducerUp.addBox(-1.5F, -8F, -1.5F, 3, 1, 3);
      ManaTransducerUp.setRotationPoint(0F, 16F, 0F);
      ManaTransducerUp.setTextureSize(128, 64);
      ManaTransducerUp.mirror = true;
      setRotation(ManaTransducerUp, 0F, 0F, 0F);
      ManaTransducerArmUp1 = new ModelRenderer(this, 65, 5);
      ManaTransducerArmUp1.addBox(-6.5F, -7F, -0.5F, 3, 1, 1);
      ManaTransducerArmUp1.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmUp1.setTextureSize(128, 64);
      ManaTransducerArmUp1.mirror = true;
      setRotation(ManaTransducerArmUp1, 0F, 0F, 0.3490659F);
      ManaTransducerArmUp2 = new ModelRenderer(this, 78, 0);
      ManaTransducerArmUp2.addBox(-0.5F, -7F, 3.5F, 1, 1, 3);
      ManaTransducerArmUp2.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmUp2.setTextureSize(128, 64);
      ManaTransducerArmUp2.mirror = true;
      setRotation(ManaTransducerArmUp2, 0.3490659F, 0F, 0F);
      ManaTransducerArmUp3 = new ModelRenderer(this, 65, 8);
      ManaTransducerArmUp3.addBox(3.5F, -7F, -0.5F, 3, 1, 1);
      ManaTransducerArmUp3.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmUp3.setTextureSize(128, 64);
      ManaTransducerArmUp3.mirror = true;
      setRotation(ManaTransducerArmUp3, 0F, 0F, -0.3490659F);
      ManaTransducerArmUp4 = new ModelRenderer(this, 78, 5);
      ManaTransducerArmUp4.addBox(-0.5F, -7F, -6.5F, 1, 1, 3);
      ManaTransducerArmUp4.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmUp4.setTextureSize(128, 64);
      ManaTransducerArmUp4.mirror = true;
      setRotation(ManaTransducerArmUp4, -0.3490659F, 0F, 0F);
      ManaTransducerDown = new ModelRenderer(this, 65, 14);
      ManaTransducerDown.addBox(-1.5F, 7F, -1.5F, 3, 1, 3);
      ManaTransducerDown.setRotationPoint(0F, 16F, 0F);
      ManaTransducerDown.setTextureSize(128, 64);
      ManaTransducerDown.mirror = true;
      setRotation(ManaTransducerDown, 0F, 0F, 0F);
      ManaTransducerArmDown1 = new ModelRenderer(this, 65, 19);
      ManaTransducerArmDown1.addBox(-6.5F, 6F, -0.5F, 3, 1, 1);
      ManaTransducerArmDown1.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmDown1.setTextureSize(128, 64);
      ManaTransducerArmDown1.mirror = true;
      setRotation(ManaTransducerArmDown1, 0F, 0F, -0.3490659F);
      ManaTransducerArmDown2 = new ModelRenderer(this, 78, 14);
      ManaTransducerArmDown2.addBox(-0.5F, 6F, -6.5F, 1, 1, 3);
      ManaTransducerArmDown2.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmDown2.setTextureSize(128, 64);
      ManaTransducerArmDown2.mirror = true;
      setRotation(ManaTransducerArmDown2, 0.3490659F, 0F, 0F);
      ManaTransducerArmDown3 = new ModelRenderer(this, 78, 19);
      ManaTransducerArmDown3.addBox(3.5F, 6F, -0.5F, 3, 1, 1);
      ManaTransducerArmDown3.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmDown3.setTextureSize(128, 64);
      ManaTransducerArmDown3.mirror = true;
      setRotation(ManaTransducerArmDown3, 0F, 0F, 0.3490659F);
      ManaTransducerArmDown4 = new ModelRenderer(this, 65, 22);
      ManaTransducerArmDown4.addBox(-0.5F, 6F, 3.5F, 1, 1, 3);
      ManaTransducerArmDown4.setRotationPoint(0F, 16F, 0F);
      ManaTransducerArmDown4.setTextureSize(128, 64);
      ManaTransducerArmDown4.mirror = true;
      setRotation(ManaTransducerArmDown4, -0.3490659F, 0F, 0F);
  }
  
  public void render(float f5)
  {
    Center1.render(f5);
    Center2.render(f5);
    Center3.render(f5);
    Center4.render(f5);
    Center5.render(f5);
    Center6.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
